title: Continuous Analysis
description: Computational reproducibility using Continuous Integration to produce verifiable end-to-end runs of scientific analysis.
show_downloads: false
google_analytics: UA-93577302-1
theme: jekyll-theme-minimal
